# Generated by Django 4.2.7 on 2025-11-23 07:59

import apps.projects.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable project code",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[apps.projects.validators.validate_project_name],
                    ),
                ),
                ("client_name", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_project_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(
                        validators=[apps.projects.validators.validate_version_number]
                    ),
                ),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "project_name",
                    models.CharField(
                        max_length=255,
                        validators=[apps.projects.validators.validate_project_name],
                    ),
                ),
                ("client_name", models.CharField(blank=True, max_length=255)),
                (
                    "project_description",
                    models.TextField(
                        blank=True,
                        validators=[
                            apps.projects.validators.validate_project_description
                        ],
                    ),
                ),
                ("reference_no", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "project_priority",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Normal", "Normal"),
                            ("High", "High"),
                            ("Urgent", "Urgent"),
                        ],
                        default="Normal",
                        max_length=20,
                    ),
                ),
                ("deadline_date", models.DateField(blank=True, null=True)),
                (
                    "project_folder_link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[apps.projects.validators.validate_url_format],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="projects.projectgroup",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        help_text="Document/Drawing number",
                        max_length=20,
                        validators=[apps.projects.validators.validate_drawing_number],
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[apps.projects.validators.validate_drawing_title],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("discipline", models.CharField(blank=True, max_length=100)),
                ("revision", models.CharField(blank=True, max_length=10)),
                (
                    "file_path",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PENDING_REVIEW", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUIRED", "Revision Required"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "documents",
                "ordering": ["document_number"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REVISION_REQUESTED", "Revision Requested"),
                            ("RESCINDED", "Rescinded"),
                            ("OBSOLETED", "Made Obsolete"),
                        ],
                        max_length=50,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=30, null=True)),
                ("to_status", models.CharField(max_length=30)),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        validators=[apps.projects.validators.validate_comments_length],
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_history",
                        to="projects.document",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_history",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "approval_history",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PROJECT_CREATED", "Project Created"),
                            ("PROJECT_UPDATED", "Project Updated"),
                            ("DOCUMENT_ADDED", "Document Added"),
                            ("DOCUMENT_UPDATED", "Document Updated"),
                            ("DOCUMENT_REMOVED", "Document Removed"),
                            ("SUBMISSION_CREATED", "Submission Created"),
                            ("VERSION_CREATED", "New Version Created"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Before/after snapshots, additional data",
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_logs",
                        to="projects.document",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_history_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_history",
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["project"], name="project_his_project_b2d99f_idx"
                    ),
                    models.Index(
                        fields=["document"], name="project_his_documen_4f50c2_idx"
                    ),
                    models.Index(
                        fields=["performed_by"], name="project_his_perform_58aa4a_idx"
                    ),
                    models.Index(
                        fields=["performed_at"], name="project_his_perform_74521b_idx"
                    ),
                    models.Index(
                        fields=["event_type"], name="project_his_event_t_398a5d_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="projectgroup",
            index=models.Index(
                fields=["created_by"], name="project_gro_created_92a956_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectgroup",
            index=models.Index(
                fields=["client_name"], name="project_gro_client__63421c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["project_group"], name="projects_project_a6139c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["created_by"], name="projects_created_428cb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["is_latest"], name="projects_is_late_b378ce_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("project_group", "version_number")},
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["project"], name="documents_project_a19858_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["created_by"], name="documents_created_32bb74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["status"], name="documents_status_f31a08_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["discipline"], name="documents_discipl_9494b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="document",
            unique_together={("project", "document_number")},
        ),
        migrations.AddIndex(
            model_name="approvalhistory",
            index=models.Index(
                fields=["project"], name="approval_hi_project_e4cf47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalhistory",
            index=models.Index(
                fields=["document"], name="approval_hi_documen_5ef452_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalhistory",
            index=models.Index(
                fields=["performed_by"], name="approval_hi_perform_cac482_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalhistory",
            index=models.Index(
                fields=["performed_at"], name="approval_hi_perform_98f597_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalhistory",
            index=models.Index(fields=["action"], name="approval_hi_action_263962_idx"),
        ),
    ]
