# Generated by Django 4.2.7 on 2025-11-23 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


def create_project_groups_from_existing_projects(apps, schema_editor):
    """Create project groups from existing projects"""
    db_alias = schema_editor.connection.alias
    
    # Use raw SQL to get existing project data
    from django.db import connection
    cursor = connection.cursor()
    
    # Check if project_groups table has data already
    cursor.execute("SELECT COUNT(*) FROM project_groups")
    existing_count = cursor.fetchone()[0]
    
    if existing_count > 0:
        print(f"Project groups already exist ({existing_count} records). Skipping creation.")
        return
    
    # Get unique projects (by name) to create project groups
    cursor.execute("""
        SELECT DISTINCT project_name, created_by_id, created_at, '' as client_name
        FROM projects
        ORDER BY created_at
    """)
    
    unique_projects = cursor.fetchall()
    
    project_group_mapping = {}
    
    for project_name, created_by_id, created_at, client_name in unique_projects:
        # Create project group (remove dashes for CHAR(32) compatibility)
        group_id = str(uuid.uuid4()).replace('-', '')
        cursor.execute("""
            INSERT INTO project_groups (id, code, name, client_name, created_by_id, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """, [group_id, '', project_name, client_name, created_by_id, created_at, created_at])
        
        project_group_mapping[project_name] = group_id
        print(f"Created project group: {project_name} -> {group_id}")


def transform_projects_table(apps, schema_editor):
    """Transform projects table to match new schema"""
    from django.db import connection
    cursor = connection.cursor()
    
    # Get project group mapping
    cursor.execute("SELECT name, id FROM project_groups")
    project_group_mapping = {name: id for name, id in cursor.fetchall()}
    
    # Check what columns exist and get existing projects 
    cursor.execute("DESCRIBE projects")
    columns = [row[0] for row in cursor.fetchall()]
    
    # Build dynamic SELECT based on available columns
    select_columns = ['id', 'project_name', 'created_by_id', 'created_at', 'updated_at']
    optional_columns = [
        ('project_description', '""'), 
        ('project_priority', '"Normal"'),
        ('deadline_date', 'NULL'),
        ('project_folder_link', '""')
    ]
    
    for col, default in optional_columns:
        if col in columns:
            select_columns.append(col)
        else:
            select_columns.append(f'{default} as {col}')
    
    # Add version_number (default to 1 if not exists)
    if 'version_number' in columns:
        select_columns.append('version_number')
    else:
        select_columns.append('1 as version_number')
    
    query = f"SELECT {', '.join(select_columns)} FROM projects"
    cursor.execute(query)
    
    existing_projects = cursor.fetchall()
    
    # Clear the projects table
    cursor.execute("DELETE FROM projects")
    
    # Drop foreign key constraints first
    try:
        cursor.execute("ALTER TABLE projects DROP FOREIGN KEY projects_reviewed_by_id_70b45ada_fk_auth_user_id")
    except:
        pass  # Constraint might not exist
    
    try:
        cursor.execute("ALTER TABLE projects DROP FOREIGN KEY projects_created_by_id_7e51a33d_fk_auth_user_id")
    except:
        pass  # Constraint might not exist
    
    # Drop old columns (with error handling for columns that might not exist)
    columns_to_drop = ['date_created', 'date_submitted', 'date_reviewed', 
                      'no_of_drawings', 'status', 'review_comments', 
                      'revision_notes', 'reviewed_by_id', 'version']
    
    for column in columns_to_drop:
        try:
            cursor.execute(f"ALTER TABLE projects DROP COLUMN {column}")
            print(f"Dropped column: {column}")
        except Exception as e:
            print(f"Column {column} does not exist or already dropped: {e}")
    
    # Add new columns (with error handling for columns that might already exist)
    columns_to_add = [
        ('project_group_id', 'CHAR(32) NOT NULL'),
        ('version_number', 'INT NOT NULL'),
        ('is_latest', 'BOOLEAN NOT NULL DEFAULT 1'),
        ('reference_no', 'VARCHAR(100) DEFAULT ""'),
        ('notes', 'LONGTEXT'),
        ('client_name', 'VARCHAR(255) DEFAULT ""')
    ]
    
    for column_name, column_def in columns_to_add:
        try:
            cursor.execute(f"ALTER TABLE projects ADD COLUMN {column_name} {column_def}")
            print(f"Added column: {column_name}")
        except Exception as e:
            print(f"Column {column_name} already exists or error: {e}")
    
    # Add foreign key constraints (with error handling)
    try:
        cursor.execute("""
            ALTER TABLE projects 
            ADD CONSTRAINT projects_project_group_id_fk 
            FOREIGN KEY (project_group_id) REFERENCES project_groups (id)
        """)
        print("Added foreign key constraint: projects_project_group_id_fk")
    except Exception as e:
        print(f"Foreign key constraint projects_project_group_id_fk already exists or error: {e}")
    
    try:
        cursor.execute("""
            ALTER TABLE projects 
            ADD CONSTRAINT projects_created_by_id_fk 
            FOREIGN KEY (created_by_id) REFERENCES auth_user (id)
        """)
        print("Added foreign key constraint: projects_created_by_id_fk")
    except Exception as e:
        print(f"Foreign key constraint projects_created_by_id_fk already exists or error: {e}")
    
    # Insert transformed data
    for project_data in existing_projects:
        # Handle dynamic field ordering
        project_dict = dict(zip([col.split(' as ')[-1] for col in select_columns], project_data))
        
        project_group_id = project_group_mapping.get(project_dict['project_name'])
        if project_group_id:
            cursor.execute("""
                INSERT INTO projects (
                    id, project_group_id, project_name, project_description, version_number,
                    is_latest, reference_no, notes, project_priority, deadline_date,
                    project_folder_link, client_name, created_by_id, created_at, updated_at
                ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """, [
                project_dict['id'], project_group_id, project_dict['project_name'], 
                project_dict.get('project_description', ''), project_dict.get('version_number', 1),
                True, '', '', project_dict.get('project_priority', 'Normal'), 
                project_dict.get('deadline_date'), project_dict.get('project_folder_link', ''), 
                '', project_dict['created_by_id'], project_dict['created_at'], project_dict['updated_at']
            ])
            print(f"Transformed project: {project_dict['project_name']}")


def transform_drawings_to_documents(apps, schema_editor):
    """Transform drawings table to documents table"""
    from django.db import connection
    cursor = connection.cursor()
    
    # Check if documents table already exists
    cursor.execute("SHOW TABLES LIKE 'documents'")
    if cursor.fetchone():
        print("Documents table already exists. Skipping transformation.")
        return
    
    # Create documents table based on drawings
    cursor.execute("""
        CREATE TABLE documents (
            id CHAR(32) PRIMARY KEY,
            project_id CHAR(32) NOT NULL,
            document_number VARCHAR(20) NOT NULL,
            title VARCHAR(255) DEFAULT '',
            description LONGTEXT,
            discipline VARCHAR(100) DEFAULT '',
            revision VARCHAR(10) DEFAULT '',
            file_path VARCHAR(100) DEFAULT '',
            status VARCHAR(20) DEFAULT 'DRAFT',
            created_by_id INT NOT NULL,
            updated_by_id INT NULL,
            created_at DATETIME(6) NOT NULL,
            updated_at DATETIME(6) NOT NULL,
            FOREIGN KEY (project_id) REFERENCES projects (id),
            FOREIGN KEY (created_by_id) REFERENCES auth_user (id),
            FOREIGN KEY (updated_by_id) REFERENCES auth_user (id)
        )
    """)
    
    # Transfer data from drawings to documents
    cursor.execute("""
        INSERT INTO documents (
            id, project_id, document_number, title, description, discipline,
            revision, file_path, status, created_by_id, updated_by_id, 
            created_at, updated_at
        )
        SELECT 
            id, project_id, drawing_no, drawing_title, drawing_description, 'General',
            CAST(revision_number AS CHAR), '', 
            CASE 
                WHEN status = 'Draft' THEN 'DRAFT'
                WHEN status = 'Submitted' THEN 'SUBMITTED'
                WHEN status = 'Approved' THEN 'APPROVED'
                WHEN status = 'Rejected' THEN 'REJECTED'
                ELSE 'DRAFT'
            END,
            added_by_id, NULL, date_added, date_added
        FROM drawings
    """)
    
    print("Transformed drawings to documents")


def reverse_transform(apps, schema_editor):
    """Reverse the transformation if needed"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Run data transformation
        migrations.RunPython(create_project_groups_from_existing_projects, reverse_transform),
        migrations.RunPython(transform_projects_table, reverse_transform),
        migrations.RunPython(transform_drawings_to_documents, reverse_transform),
    ]
