# Generated by Django 4.2.7 on 2025-06-24 08:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="drawing",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="project",
            name="project_group_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Groups different versions of the same project.",
            ),
        ),
        migrations.AlterField(
            model_name="approvalhistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Submitted", "Submitted"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Resubmitted", "Resubmitted"),
                    ("Status_Changed", "Status Changed"),
                    ("Obsoleted", "Obsoleted"),
                    ("Version_Created", "Version Created"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["project_group_id"], name="projects_project_a6139c_idx"
            ),
        ),
    ]
