# Generated by Django 4.2.7 on 2025-11-23 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_auto_20251123_1928"),
    ]

    operations = [
        # Remove fields that don't exist in the actual database
        migrations.RemoveField(
            model_name='projecthistory',
            name='document',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='projecthistory',
            name='performed_at',
        ),
        # Add fields that exist in the actual database
        migrations.AddField(
            model_name='projecthistory',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='submission_link',
            field=models.URLField(max_length=500, blank=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='drawing_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='drawing_numbers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='receipt_id',
            field=models.CharField(max_length=100, unique=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='approval_status',
            field=models.CharField(
                max_length=30,
                choices=[
                    ('PENDING', 'Pending'),
                    ('APPROVED', 'Approved'),
                    ('REJECTED', 'Rejected'),
                    ('REVISION_REQUIRED', 'Revision Required'),
                ],
                default='PENDING'
            ),
        ),
        migrations.AddField(
            model_name='projecthistory',
            name='submitted_by',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='project_submissions',
                to=settings.AUTH_USER_MODEL,
                default=1
            ),
            preserve_default=False,
        ),
    ]
