# Generated by Django 4.2.7 on 2025-07-07 01:45

import apps.projects.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0002_alter_drawing_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalhistory",
            name="comments",
            field=models.TextField(
                blank=True,
                validators=[
                    apps.projects.validators.validate_comments_length,
                    apps.projects.validators.validate_no_malicious_content,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="drawing_description",
            field=models.TextField(
                blank=True,
                validators=[apps.projects.validators.validate_no_malicious_content],
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="drawing_list_link",
            field=models.URLField(
                blank=True,
                max_length=500,
                validators=[apps.projects.validators.validate_url_format],
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="drawing_no",
            field=models.CharField(
                max_length=20,
                validators=[apps.projects.validators.validate_drawing_number],
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="drawing_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[apps.projects.validators.validate_drawing_title],
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="drawing_type",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[apps.projects.validators.validate_drawing_type],
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="revision_number",
            field=models.IntegerField(
                default=0,
                validators=[apps.projects.validators.validate_revision_number],
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="scale_ratio",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[apps.projects.validators.validate_scale_ratio],
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="sheet_size",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[apps.projects.validators.validate_sheet_size],
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="sort_order",
            field=models.IntegerField(
                default=0, validators=[apps.projects.validators.validate_sort_order]
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_description",
            field=models.TextField(
                blank=True,
                validators=[
                    apps.projects.validators.validate_project_description,
                    apps.projects.validators.validate_no_malicious_content,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(
                max_length=255,
                validators=[apps.projects.validators.validate_project_name],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="review_comments",
            field=models.TextField(
                blank=True,
                validators=[
                    apps.projects.validators.validate_comments_length,
                    apps.projects.validators.validate_no_malicious_content,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="revision_notes",
            field=models.TextField(
                blank=True,
                validators=[
                    apps.projects.validators.validate_comments_length,
                    apps.projects.validators.validate_no_malicious_content,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="version",
            field=models.IntegerField(
                validators=[apps.projects.validators.validate_version_number]
            ),
        ),
        migrations.CreateModel(
            name="ProjectHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.IntegerField()),
                ("date_submitted", models.DateTimeField()),
                ("submission_link", models.URLField(blank=True, max_length=500)),
                ("drawing_qty", models.IntegerField(default=0)),
                (
                    "drawing_numbers",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of drawing numbers"
                    ),
                ),
                ("receipt_id", models.CharField(blank=True, max_length=100)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Pending_Approval", "Pending Approval"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Revise_and_Resubmit", "Revise and Resubmit"),
                            ("Obsolete", "Obsolete"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_logs",
                        to="projects.project",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_history_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "project_history",
                "ordering": ["-date_submitted"],
                "indexes": [
                    models.Index(
                        fields=["project"], name="project_his_project_b2d99f_idx"
                    ),
                    models.Index(
                        fields=["submitted_by"], name="project_his_submitt_3b2c09_idx"
                    ),
                    models.Index(
                        fields=["date_submitted"], name="project_his_date_su_5bb1a4_idx"
                    ),
                    models.Index(
                        fields=["approval_status"],
                        name="project_his_approva_22e247_idx",
                    ),
                ],
            },
        ),
    ]
