# Generated by Django 4.2.7 on 2025-07-09 04:04

import apps.projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_approvalhistory_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalhistory",
            name="comments",
            field=models.TextField(
                blank=True,
                validators=[apps.projects.validators.validate_comments_length],
            ),
        ),
        migrations.AlterField(
            model_name="drawing",
            name="drawing_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_description",
            field=models.TextField(
                blank=True,
                validators=[apps.projects.validators.validate_project_description],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="review_comments",
            field=models.TextField(
                blank=True,
                validators=[apps.projects.validators.validate_comments_length],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="revision_notes",
            field=models.TextField(
                blank=True,
                validators=[apps.projects.validators.validate_comments_length],
            ),
        ),
    ]
