# Generated by Django 4.2.7 on 2025-07-09 05:47

import apps.projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_approvalhistory_comments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawing",
            name="drawing_list_link",
        ),
        migrations.AddField(
            model_name="project",
            name="project_folder_link",
            field=models.URLField(
                blank=True,
                max_length=500,
                validators=[apps.projects.validators.validate_url_format],
            ),
        ),
    ]
