# Generated by Django 4.2.7 on 2025-07-12 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_remove_drawing_drawing_list_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="client_department",
        ),
    ]
