# Generated by Django 4.2.7 on 2025-07-12 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_remove_project_client_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drawing",
            name="discipline",
        ),
        migrations.RemoveField(
            model_name="drawing",
            name="drawing_type",
        ),
    ]
