# Generated by Django 4.2.7 on 2025-07-13 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_remove_drawing_discipline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pending_Approval", "Pending Approval"),
                    ("Approved_Endorsed", "Approved & Endorsed"),
                    ("Conditional_Approval", "Conditional Approval"),
                    ("Request_for_Revision", "Request for Revision"),
                    ("Rejected", "Rejected"),
                    ("Rescinded_Revoked", "Rescinded & Revoked"),
                    ("Obsolete", "Obsolete"),
                ],
                default="Draft",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="projecthistory",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Pending_Approval", "Pending Approval"),
                    ("Approved_Endorsed", "Approved & Endorsed"),
                    ("Conditional_Approval", "Conditional Approval"),
                    ("Request_for_Revision", "Request for Revision"),
                    ("Rejected", "Rejected"),
                    ("Rescinded_Revoked", "Rescinded & Revoked"),
                    ("Obsolete", "Obsolete"),
                ],
                max_length=30,
            ),
        ),
    ]
