# Generated by Django 4.2.7 on 2025-07-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_alter_project_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalhistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Submitted", "Submitted"),
                    ("Approved_Endorsed", "Approved & Endorsed"),
                    ("Conditional_Approval", "Conditional Approval"),
                    ("Request_for_Revision", "Request for Revision"),
                    ("Rejected", "Rejected"),
                    ("Rescinded_Revoked", "Rescinded & Revoked"),
                    ("Resubmitted", "Resubmitted"),
                    ("Status_Changed", "Status Changed"),
                    ("Obsoleted", "Obsoleted"),
                    ("Version_Created", "Version Created"),
                ],
                max_length=50,
            ),
        ),
    ]
