# Generated by Django 4.2.7 on 2025-08-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_approvalhistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending_Approval', 'Pending Approval'), ('Approved_Endorsed', 'Approved & Endorsed'), ('Conditional_Approval', 'Conditional Approval'), ('Request_for_Revision', 'Request for Revision'), ('Rejected', 'Rejected'), ('Rescinded_Revoked', 'Rescinded & Revoked'), ('Obsolete', 'Obsolete')], default='Draft', max_length=20),
        ),
    ]
