# Generated by Django 4.2.7 on 2025-11-23 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_on_submission", models.BooleanField(default=True)),
                ("email_on_approval", models.BooleanField(default=True)),
                ("email_on_rejection", models.BooleanField(default=True)),
                ("email_on_revision_required", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediate"),
                            ("DAILY", "Daily Digest"),
                            ("WEEKLY", "Weekly Digest"),
                        ],
                        default="IMMEDIATE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("login_at", models.DateTimeField(auto_now_add=True)),
                ("last_active_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_sessions",
                "ordering": ["-login_at"],
                "indexes": [
                    models.Index(
                        fields=["user"], name="user_sessio_user_id_eb20aa_idx"
                    ),
                    models.Index(
                        fields=["session_key"], name="user_sessio_session_cc84b9_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="user_sessio_is_acti_1b3cb1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Engineering", "Engineering"),
                            ("Architecture", "Architecture"),
                            ("Construction", "Construction"),
                            ("Planning", "Planning"),
                            ("Quality Assurance", "Quality Assurance"),
                            ("Project Management", "Project Management"),
                            ("Administration", "Administration"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Engineer", "Engineer"),
                            ("Senior Engineer", "Senior Engineer"),
                            ("Principal Engineer", "Principal Engineer"),
                            ("Architect", "Architect"),
                            ("Senior Architect", "Senior Architect"),
                            ("Project Manager", "Project Manager"),
                            ("Team Lead", "Team Lead"),
                            ("Supervisor", "Supervisor"),
                            ("Manager", "Manager"),
                            ("Director", "Director"),
                            ("Technician", "Technician"),
                            ("Draftsperson", "Draftsperson"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("submitter", "Submitter"),
                            ("approver", "Approver"),
                            ("admin", "Admin"),
                            ("viewer", "Viewer"),
                        ],
                        default="submitter",
                        max_length=20,
                    ),
                ),
                (
                    "time_zone",
                    models.CharField(
                        choices=[
                            ("UTC", "UTC"),
                            ("Asia/Kuala_Lumpur", "Malaysia Time (MYT)"),
                            ("Asia/Singapore", "Singapore Time (SGT)"),
                            ("Asia/Jakarta", "Western Indonesia Time (WIB)"),
                        ],
                        default="Asia/Kuala_Lumpur",
                        max_length=50,
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Brief description about yourself"
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("hire_date", models.DateField(blank=True, null=True)),
                ("is_active_employee", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_profiles",
                "ordering": ["full_name"],
                "indexes": [
                    models.Index(fields=["role"], name="user_profil_role_fa03e1_idx"),
                    models.Index(
                        fields=["department"], name="user_profil_departm_d15927_idx"
                    ),
                    models.Index(
                        fields=["manager"], name="user_profil_manager_b4b523_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("template_name", models.CharField(blank=True, max_length=100)),
                (
                    "message_id",
                    models.CharField(
                        blank=True, help_text="Provider message ID", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("BOUNCED", "Bounced"),
                            ("OPENED", "Opened"),
                            ("CLICKED", "Clicked"),
                            ("FAILED", "Failed"),
                        ],
                        default="SENT",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(fields=["user"], name="email_logs_user_id_185b75_idx"),
                    models.Index(
                        fields=["to_email"], name="email_logs_to_emai_9c46ac_idx"
                    ),
                    models.Index(
                        fields=["status"], name="email_logs_status_e3be55_idx"
                    ),
                    models.Index(
                        fields=["sent_at"], name="email_logs_sent_at_9fc48d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "User Login"),
                            ("LOGOUT", "User Logout"),
                            ("PERMISSION_CHANGED", "Permission Changed"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("PROJECT_ACTION", "Project Action"),
                            ("SYSTEM_EVENT", "System Event"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Project', 'Document'",
                        max_length=100,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="audit_logs_user_id_73c422_idx"),
                    models.Index(
                        fields=["event_type"], name="audit_logs_event_t_3207df_idx"
                    ),
                    models.Index(
                        fields=["object_type"], name="audit_logs_object__69dfc3_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_logs_created_262184_idx"
                    ),
                ],
            },
        ),
    ]
