# Generated by Django 4.2.7 on 2025-06-24 07:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="userroleassignment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userroleassignment",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="userroleassignment",
            name="role",
        ),
        migrations.RemoveField(
            model_name="userroleassignment",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
        migrations.DeleteModel(
            name="UserRoleAssignment",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.role",
            ),
        ),
    ]
