# Generated by Django 4.2.7 on 2025-11-23 11:28

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


def create_user_profiles_table(apps, schema_editor):
    """Create user profiles table and populate with existing user data"""
    from django.db import connection
    cursor = connection.cursor()
    
    # Get default role (create one if needed)
    cursor.execute("SELECT id FROM accounts_role LIMIT 1")
    role_result = cursor.fetchone()
    if not role_result:
        # Create default role
        default_role_id = str(uuid.uuid4())
        cursor.execute("""
            INSERT INTO accounts_role (id, name, permissions, created_at, updated_at)
            VALUES (%s, %s, %s, NOW(), NOW())
        """, [default_role_id, 'User', '{}'])
    else:
        default_role_id = role_result[0]
    
    # Store existing user profile data if it exists
    existing_profiles = {}
    try:
        cursor.execute("SELECT user_id, department, phone_number FROM user_profiles")
        for user_id, dept, phone in cursor.fetchall():
            existing_profiles[user_id] = {'department': dept or '', 'phone_number': phone or ''}
    except:
        pass  # Table might not exist
    
    # Drop existing user_profiles table if it exists
    cursor.execute("DROP TABLE IF EXISTS user_profiles")
    
    # Create new user_profiles table
    cursor.execute("""
        CREATE TABLE user_profiles (
            id CHAR(36) PRIMARY KEY,
            user_id INT UNIQUE NOT NULL,
            role_id CHAR(36) NOT NULL,
            department VARCHAR(100) DEFAULT '',
            phone_number VARCHAR(20) DEFAULT '',
            created_at DATETIME(6) NOT NULL,
            updated_at DATETIME(6) NOT NULL,
            FOREIGN KEY (user_id) REFERENCES auth_user (id),
            FOREIGN KEY (role_id) REFERENCES accounts_role (id)
        )
    """)
    
    # Create user profiles for all existing users
    cursor.execute("SELECT id, date_joined FROM auth_user")
    users = cursor.fetchall()
    
    for user_id, date_joined in users:
        profile_id = str(uuid.uuid4())
        existing_data = existing_profiles.get(user_id, {'department': '', 'phone_number': ''})
        cursor.execute("""
            INSERT INTO user_profiles (id, user_id, role_id, department, phone_number, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
        """, [profile_id, user_id, default_role_id, existing_data['department'], 
              existing_data['phone_number'], date_joined, date_joined])
    
    print(f"Recreated user profiles for {len(users)} users")


def create_notification_preferences_table(apps, schema_editor):
    """Create notification preferences table"""
    from django.db import connection
    cursor = connection.cursor()
    
    # Store existing notification preferences if they exist
    existing_prefs = {}
    try:
        cursor.execute("SELECT user_id, email_on_submission, email_on_approval, email_on_rejection, email_on_revision_required FROM notification_preferences")
        for user_id, submission, approval, rejection, revision in cursor.fetchall():
            existing_prefs[user_id] = {
                'submission': bool(submission),
                'approval': bool(approval), 
                'rejection': bool(rejection),
                'revision': bool(revision)
            }
    except:
        pass  # Table might not exist
    
    # Drop existing notification_preferences table if it exists
    cursor.execute("DROP TABLE IF EXISTS notification_preferences")
    
    # Create new notification_preferences table
    cursor.execute("""
        CREATE TABLE notification_preferences (
            id CHAR(36) PRIMARY KEY,
            user_id INT UNIQUE NOT NULL,
            email_enabled BOOLEAN DEFAULT 1,
            submission_notifications BOOLEAN DEFAULT 1,
            approval_notifications BOOLEAN DEFAULT 1,
            rejection_notifications BOOLEAN DEFAULT 1,
            revision_notifications BOOLEAN DEFAULT 1,
            created_at DATETIME(6) NOT NULL,
            updated_at DATETIME(6) NOT NULL,
            FOREIGN KEY (user_id) REFERENCES auth_user (id)
        )
    """)
    
    # Create preferences for all existing users
    cursor.execute("SELECT id FROM auth_user")
    users = cursor.fetchall()
    
    for (user_id,) in users:
        pref_id = str(uuid.uuid4())
        existing_data = existing_prefs.get(user_id, {
            'submission': True, 'approval': True, 'rejection': True, 'revision': True
        })
        cursor.execute("""
            INSERT INTO notification_preferences (id, user_id, email_enabled, submission_notifications, 
                                               approval_notifications, rejection_notifications, 
                                               revision_notifications, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, NOW(), NOW())
        """, [pref_id, user_id, True, existing_data['submission'], existing_data['approval'], 
              existing_data['rejection'], existing_data['revision']])
    
    print(f"Recreated notification preferences for {len(users)} users")


def create_additional_tables(apps, schema_editor):
    """Create email logs, user sessions, and audit logs tables"""
    from django.db import connection
    cursor = connection.cursor()
    
    # Email logs table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS email_logs (
            id CHAR(36) PRIMARY KEY,
            recipient_id INT NOT NULL,
            subject VARCHAR(255) NOT NULL,
            body LONGTEXT NOT NULL,
            sent_at DATETIME(6) NOT NULL,
            status VARCHAR(20) DEFAULT 'sent',
            error_message LONGTEXT,
            FOREIGN KEY (recipient_id) REFERENCES auth_user (id)
        )
    """)
    
    # User sessions table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS user_sessions (
            id CHAR(36) PRIMARY KEY,
            user_id INT NOT NULL,
            session_key VARCHAR(40) NOT NULL,
            ip_address VARCHAR(45) DEFAULT '',
            user_agent LONGTEXT,
            created_at DATETIME(6) NOT NULL,
            last_activity DATETIME(6) NOT NULL,
            is_active BOOLEAN DEFAULT 1,
            FOREIGN KEY (user_id) REFERENCES auth_user (id)
        )
    """)
    
    # Audit logs table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS audit_logs (
            id CHAR(36) PRIMARY KEY,
            user_id INT NULL,
            action VARCHAR(100) NOT NULL,
            model_name VARCHAR(100) DEFAULT '',
            object_id VARCHAR(36) DEFAULT '',
            changes LONGTEXT,
            ip_address VARCHAR(45) DEFAULT '',
            user_agent LONGTEXT,
            performed_at DATETIME(6) NOT NULL,
            FOREIGN KEY (user_id) REFERENCES auth_user (id)
        )
    """)
    
    print("Created additional tables: email_logs, user_sessions, audit_logs")


def reverse_accounts_transform(apps, schema_editor):
    """Reverse the transformation if needed"""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create the missing tables
        migrations.RunPython(create_user_profiles_table, reverse_accounts_transform),
        migrations.RunPython(create_notification_preferences_table, reverse_accounts_transform),
        migrations.RunPython(create_additional_tables, reverse_accounts_transform),
    ]
