# Generated by Django 4.2.7 on 2025-06-24 07:18

from django.db import migrations

def create_roles(apps, schema_editor):
    """
    Creates the initial roles for the application.
    """
    Role = apps.get_model('accounts', 'Role')
    
    roles_to_create = [
        Role(name='Admin', description='Has all permissions, including user management.'),
        Role(name='Approver', description='Can review and approve/reject project submissions.'),
        Role(name='Submitter', description='Can create and submit projects for approval.'),
        Role(name='Viewer', description='Has read-only access to view projects.'),
    ]
    
    Role.objects.bulk_create(roles_to_create)

class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_role_alter_userroleassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
