# Generated by Django 4.2.7 on 2025-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Approver', 'Approver'), ('Submitter', 'Submitter'), ('Viewer', 'Viewer')], max_length=50, unique=True),
        ),
    ]
