# Generated by Django 4.2.7 on 2025-11-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.CharField(
                        help_text="e.g., 1.0.0", max_length=20, unique=True
                    ),
                ),
                (
                    "version_type",
                    models.CharField(
                        choices=[
                            ("major", "Major Release"),
                            ("minor", "Minor Release"),
                            ("patch", "Patch Release"),
                            ("beta", "Beta Release"),
                        ],
                        default="minor",
                        max_length=10,
                    ),
                ),
                ("release_date", models.DateTimeField(auto_now_add=True)),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, help_text="Mark as current version"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of this version"
                    ),
                ),
            ],
            options={
                "verbose_name": "Version",
                "verbose_name_plural": "Versions",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="VersionImprovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "improvement_type",
                    models.CharField(
                        choices=[
                            ("feature", "New Feature"),
                            ("enhancement", "Enhancement"),
                            ("bugfix", "Bug Fix"),
                            ("security", "Security Fix"),
                            ("performance", "Performance Improvement"),
                            ("ui", "UI/UX Improvement"),
                            ("api", "API Change"),
                            ("documentation", "Documentation"),
                        ],
                        default="feature",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of display"
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improvements",
                        to="core.version",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version Improvement",
                "verbose_name_plural": "Version Improvements",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
