# Generated by Django 4.2.7 on 2025-07-07 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0003_alter_approvalhistory_comments_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("notify_submission", models.BooleanField(default=True)),
                ("notify_approval", models.BooleanField(default=True)),
                ("notify_rejection", models.BooleanField(default=True)),
                ("notify_revision_request", models.BooleanField(default=True)),
                ("notify_obsolete", models.BooleanField(default=True)),
                ("notify_admin_new_submission", models.BooleanField(default=True)),
                ("notify_admin_resubmission", models.BooleanField(default=True)),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("IMMEDIATE", "Immediate"),
                            ("DAILY", "Daily Digest"),
                            ("WEEKLY", "Weekly Digest"),
                            ("DISABLED", "Disabled"),
                        ],
                        default="IMMEDIATE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("recipient_name", models.CharField(blank=True, max_length=255)),
                ("template_type", models.CharField(max_length=50)),
                ("template_id", models.IntegerField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("BOUNCED", "Bounced"),
                            ("SPAM", "Spam"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("brevo_message_id", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "db_table": "email_logs",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["project"], name="email_logs_project_c3191c_idx"
                    ),
                    models.Index(
                        fields=["recipient_email"], name="email_logs_recipie_00ae8d_idx"
                    ),
                    models.Index(
                        fields=["sent_at"], name="email_logs_sent_at_9fc48d_idx"
                    ),
                    models.Index(
                        fields=["status"], name="email_logs_status_e3be55_idx"
                    ),
                ],
            },
        ),
    ]
